// Moves the legal pages that were hardcoded under frontend/src/pages
// (PrivacyPolicy, TermsAndConditions, RefundPolicy) into the LegalPage
// collection, so their text becomes editable without a redeploy. Nodal Officer
// is a separate CMS module (see migrateNodalOfficers.js).
//
// The slugs match the existing footer routes exactly, so the frontend keeps
// resolving /privacy-policy, /refund-policy and /terms-and-conditions by slug
// with no route change.
//
// Idempotent: matched on slug, so re-running updates rather than duplicates.
// Existing rows keep their status and — importantly — their edited content:
// only newly created pages get the seed body, so re-running never overwrites a
// page an editor has since changed.
const LegalPage = require('../src/models/LegalPage');
const { upsertOne } = require('./helpers/upsert');
const logger = require('./helpers/logger');

// The download icon is copied from what lucide-react renders, inlined so the
// migrated refund button is visually identical to the original component.
const icon = {
    download: '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/></svg>'
};

const PRIVACY = `
<p>The Privacy Policy and User Agreement is made to meet the requirement of the Information Technology Act 2000. Being the electronic record under Information Technology Act, 2000, this document is generated by a computer system and does not require any physical or digital signatures.</p>
<p>Your use of this website is governed by this contract. You shall have deemed to have agreed to be bound by this privacy policy and user agreement, whenever you access or use this site in any way. Surjit Finance respects the privacy of visitors to this website. This policy describes how and when we gather information from visitors to our website.</p>
<h2>Information Collection</h2>
<p>Through our website, while surfing generally, we do not record any sensitive personal data of users. In case user is interested in filing of form for the purpose getting some more information about our product or services, we require certain information like name, address, mobile no. and email id to be provided by the user, subsequently, which is shared with our team, by providing them, user agrees to be called by the responsible person. We may also require some information for the purpose of getting the credit details of the user. In line with our privacy policy we respect the privacy of our users and utmost care is taken to keep the information safe and use them only for the purposes these have been collected.</p>
<h2>Data Usage</h2>
<p>Personally identifiable information such as name and contact details are collected by us in the form of applications or web forms. By voluntarily providing details, user agrees to get calls from Surjit Finance for the purpose of receiving detailed information about our products and services. We sometimes, in the course of our business, get the credit information of the user from the external websites, by providing the data collected from the users, however these external websites are safe.</p>
<h2>Third Party Disclosure</h2>
<p>We employ staffs for the purpose of handling work on our behalf. We also take the assistance of outsiders to maintain or operate the website. These persons may have personal identifiable information to perform the work on behalf of the Surjit Finance, however such information may be used by them only in performance of their duties and not for any other purpose.</p>
<p>We will not provide any personal information collected though our website, to any other person, except in pursuance of this privacy policy and user agreement and in furtherance of user's request or in compliance of an order of court or any government authority and user agrees or authorises us to do so.</p>
<h2>Intellectual Property</h2>
<p>This website including its contents is the intellectual property of Surjit Finance and no portion of this website, except to the extent allowed hereunder, can be copied, sorted, duplicated, manipulated, published or disseminated by any other person for any purpose. Any user may use the content of this website only for their personal purposes and unless permitted in writing by us, cannot use for commercial purpose or to disseminate or publish, the content on any other website or media.</p>
<h2>Disclaimer</h2>
<p>Further users are advised to verify, before using the content published on the website, from their personal sources. Surjit Finance does not guarantee the veracity or usefulness or result of the information displayed on the website. Surjit Finance or any of its director or employee is not responsible for any loss or damage caused to any person by the reason of opening or using or relying of the information or contents or any external link published or displayed on the website.</p>
<h2>Customer Consent</h2>
<p>This website is not intended to be accessed or viewed outside India and because of international nature of the internet the responsibility of complying the local laws of the country outside India is of the viewer only. Surjit Finance is no way responsible for complying the laws nor authorise anybody to access the website in any country other than India.</p>
<p>User by opening the website in its device agree to privacy policy and abide by the terms conditions of the website. Place of jurisdictions of any matter arising out of this privacy policy and user agreement shall be Lucknow only.</p>
`.trim();

const TERMS = `
<p>Welcome to Surjit Finance. These Terms and Conditions govern your use of our website and services. By accessing or using our website, you agree to comply with and be bound by these terms. If you do not agree with any part of these terms, please do not use our website.</p>
<h2>1. Acceptance of Terms</h2>
<p>By accessing this website, we assume you accept these terms and conditions in full. Do not continue to use Surjit Finance's website if you do not accept all of the terms and conditions stated on this page.</p>
<h2>2. Intellectual Property Rights</h2>
<p>Unless otherwise stated, Surjit Finance and/or its licensors own the intellectual property rights for all material on Surjit Finance. All intellectual property rights are reserved. You may view and/or print pages from https://www.surjitfinance.com for your own personal use subject to restrictions set in these terms and conditions.</p>
<p>You must not:</p>
<ul>
<li>Republish material from this website</li>
<li>Sell, rent or sub-license material from the website</li>
<li>Reproduce, duplicate or copy material from the website</li>
<li>Redistribute content from Surjit Finance (unless content is specifically made for redistribution)</li>
</ul>
<h2>3. User Conduct</h2>
<p>You agree to use the website only for lawful purposes and in a way that does not infringe the rights of, restrict or inhibit anyone else's use and enjoyment of the website. Prohibited behavior includes harassing or causing distress or inconvenience to any other user, transmitting obscene or offensive content or disrupting the normal flow of dialogue within our website.</p>
<h2>4. Loan Applications and Services</h2>
<p>All loan applications submitted through this website are subject to Surjit Finance's credit approval process. Providing information through the web forms does not guarantee the approval of any financial product. Surjit Finance reserves the right to reject any application without providing a reason.</p>
<h2>5. Limitation of Liability</h2>
<p>Surjit Finance will not be liable for any loss or damage of any nature. We do not warrant that the website will be constantly available, or available at all; or that the information on this website is complete, true, accurate or non-misleading.</p>
<h2>6. External Links</h2>
<p>Our website may contain links to third-party websites or services that are not owned or controlled by Surjit Finance. Surjit Finance has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third-party websites or services.</p>
<h2>7. Governing Law</h2>
<p>These terms and conditions are governed by and construed in accordance with the laws of India and you irrevocably submit to the exclusive jurisdiction of the courts in Lucknow, Uttar Pradesh.</p>
<h2>8. Changes to Terms</h2>
<p>Surjit Finance reserves the right to revise these terms and conditions at any time as it sees fit, and by using this website you are expected to review such terms on a regular basis to ensure you understand all terms and conditions governing use of this website.</p>
<h2>9. Contact Us</h2>
<p>If you have any questions about our Terms and Conditions, please contact us at info@surjitfinance.com or our toll-free number 1800-3131-265.</p>
`.trim();

// The refund page is download-oriented. The button links directly to the policy
// PDF, exactly as the original page did — a site-relative /api path would resolve
// against the website origin, not the API subdomain, in production. The same URL
// is stored in the `pdf` field, so the /download endpoint also serves it (302)
// and an admin can later replace it by uploading a file through the CMS.
const REFUND_PDF_URL = 'https://www.surjitfinance.com/wp-content/uploads/2024/02/refund-policy.pdf';
const REFUND = `
<div style="text-align:center">
<h2>Refund Policy</h2>
<p>Please refer to our detailed refund policy document for complete information about our refund and cancellation procedures.</p>
<a href="${REFUND_PDF_URL}" target="_blank" rel="noopener noreferrer" class="btn btn-primary btn-lg" style="margin-top:2rem">${icon.download} Download Refund Policy</a>
<div style="margin-top:3rem;padding:2rem;background:var(--gray-50);border-radius:var(--radius-xl)">
<h3 style="margin-bottom:1rem">Key Points</h3>
<ul style="text-align:left;max-width:500px;margin:0 auto">
<li>Refund requests must be submitted within the specified timeframe</li>
<li>Processing fees may be non-refundable in certain cases</li>
<li>Refunds are processed within 7-10 business days</li>
<li>For queries, contact us at 1800-3131-265</li>
</ul>
</div>
</div>
`.trim();

const PAGES = [
    {
        type: 'privacy', slug: 'privacy-policy', title: 'Privacy Policy',
        description: '', content: PRIVACY,
        seoTitle: 'Privacy Policy', seoDescription: 'How Surjit Finance collects, uses and protects the information of visitors to its website.'
    },
    {
        type: 'refund', slug: 'refund-policy', title: 'Refund Policy',
        description: '', content: REFUND,
        pdf: { url: REFUND_PDF_URL, fileName: '', size: 0, originalName: 'refund-policy.pdf' },
        seoTitle: 'Refund Policy', seoDescription: 'Surjit Finance refund and cancellation policy.'
    },
    {
        type: 'terms', slug: 'terms-and-conditions', title: 'Terms & Conditions',
        description: '', content: TERMS,
        seoTitle: 'Terms & Conditions', seoDescription: 'The terms and conditions governing use of the Surjit Finance website and services.'
    }
];

module.exports = async (ctx) => {
    let created = 0;
    let updated = 0;

    for (const [index, page] of PAGES.entries()) {
        const existing = await LegalPage.findOne({ slug: page.slug });

        // Never clobber an edited page: for existing rows only keep them in place
        // (and refresh nothing), so an admin's changes survive a re-run.
        const data = existing
            ? {}
            : { ...page, displayOrder: index + 1, status: 'Published' };

        const { doc } = await upsertOne(LegalPage, { slug: page.slug }, data, ctx);

        if (existing) updated += 1; else created += 1;
        logger.info(`  ${existing ? 'kept   ' : 'created'}  ${doc.title} (${doc.slug}) — ${doc.status}`);
    }

    return `${created} created, ${updated} kept`;
};

// Allow `node scripts/migrateLegalPages.js` on its own.
if (require.main === module) {
    const { connect, disconnect } = require('./helpers/db');
    const { MigrationContext } = require('./helpers/upsert');

    (async () => {
        const ctx = new MigrationContext('legal-pages');
        try {
            await connect();
            logger.success('Connected to MongoDB');
            const summary = await module.exports(ctx);
            logger.success(`Legal pages: ${summary}`);
        } catch (err) {
            logger.error(err.message);
            const removed = await ctx.rollback();
            logger.warn(`Rolled back ${removed} newly-created record(s).`);
            process.exitCode = 1;
        } finally {
            await disconnect();
        }
    })();
}
