import './PrivacyPolicy.css';

const PrivacyPolicy = () => {
    return (
        <div className="policy-page">
            <section className="policy-hero">
                <div className="container">
                    <h1>Privacy Policy</h1>
                </div>
            </section>

            <section className="policy-content section">
                <div className="container">
                    <div className="policy-card">
                        <p>
                            The Privacy Policy and User Agreement is made to meet the requirement of the Information Technology Act 2000. Being the electronic record under Information Technology Act, 2000, this document is generated by a computer system and does not require any physical or digital signatures.
                        </p>

                        <p>
                            Your use of this website is governed by this contract. You shall have deemed to have agreed to be bound by this privacy policy and user agreement, whenever you access or use this site in any way. Surjit Finance respects the privacy of visitors to this website. This policy describes how and when we gather information from visitors to our website.
                        </p>

                        <h2>Information Collection</h2>
                        <p>
                            Through our website, while surfing generally, we do not record any sensitive personal data of users. In case user is interested in filing of form for the purpose getting some more information about our product or services, we require certain information like name, address, mobile no. and email id to be provided by the user, subsequently, which is shared with our team, by providing them, user agrees to be called by the responsible person. We may also require some information for the purpose of getting the credit details of the user. In line with our privacy policy we respect the privacy of our users and utmost care is taken to keep the information safe and use them only for the purposes these have been collected.
                        </p>

                        <h2>Data Usage</h2>
                        <p>
                            Personally identifiable information such as name and contact details are collected by us in the form of applications or web forms. By voluntarily providing details, user agrees to get calls from Surjit Finance for the purpose of receiving detailed information about our products and services. We sometimes, in the course of our business, get the credit information of the user from the external websites, by providing the data collected from the users, however these external websites are safe.
                        </p>

                        <h2>Third Party Disclosure</h2>
                        <p>
                            We employ staffs for the purpose of handling work on our behalf. We also take the assistance of outsiders to maintain or operate the website. These persons may have personal identifiable information to perform the work on behalf of the Surjit Finance, however such information may be used by them only in performance of their duties and not for any other purpose.
                        </p>

                        <p>
                            We will not provide any personal information collected though our website, to any other person, except in pursuance of this privacy policy and user agreement and in furtherance of user's request or in compliance of an order of court or any government authority and user agrees or authorises us to do so.
                        </p>

                        <h2>Intellectual Property</h2>
                        <p>
                            This website including its contents is the intellectual property of Surjit Finance and no portion of this website, except to the extent allowed hereunder, can be copied, sorted, duplicated, manipulated, published or disseminated by any other person for any purpose. Any user may use the content of this website only for their personal purposes and unless permitted in writing by us, cannot use for commercial purpose or to disseminate or publish, the content on any other website or media.
                        </p>

                        <h2>Disclaimer</h2>
                        <p>
                            Further users are advised to verify, before using the content published on the website, from their personal sources. Surjit Finance does not guarantee the veracity or usefulness or result of the information displayed on the website. Surjit Finance or any of its director or employee is not responsible for any loss or damage caused to any person by the reason of opening or using or relying of the information or contents or any external link published or displayed on the website.
                        </p>

                        <h2>Customer Consent</h2>
                        <p>
                            This website is not intended to be accessed or viewed outside India and because of international nature of the internet the responsibility of complying the local laws of the country outside India is of the viewer only. Surjit Finance is no way responsible for complying the laws nor authorise anybody to access the website in any country other than India.
                        </p>

                        <p>
                            User by opening the website in its device agree to privacy policy and abide by the terms conditions of the website. Place of jurisdictions of any matter arising out of this privacy policy and user agreement shall be Lucknow only.
                        </p>
                    </div>
                </div>
            </section>
        </div>
    );
};

export default PrivacyPolicy;
